### ISSUE TITLE
AmericanSeason&BlackholeInverter suggestions

### ISSUE THREAD

**Issue by sanscriptum** [klattmose/klattmose.github.io#18]
1. Add achievements for having 550 and 600 Blackhole Inverters, like the rest of the buildings. Also move BI achievements so they're placed after Idleverses, though it might be a bit too late for that save compatibility wise? (I'm curious if building biscuits also require having BIs?)
2. Add two last tiers of upgrades and fortune upgrade for BIs. Also synergy boost is a bit lackluster compared to others, as it buffs two very weak buildings, oh well.
3. The initial speed of the rocket in the season is a bit too fast. Since you have to work with vertical space which is usually smaller, it gives you about 2-3 seconds to react and click before it goes away. I tend to catch it in the middle of the screen. It's not too bad overall, maybe 5% speed decrease would be nice.
4. Fireworks performance is rather sad, not sure what can be done about it. One of the types doesn't seem to slow down the game though.
5. I wonder if it's possible to add a new plant that boosts rockets, similar to Chimerose that boosts reindeer.
6. Add a new dragon aura tied to BI. No idea what kind of though.

**Comment by klattmose** [comment]
I'll be honest: I mostly just made those mods just to see if it was possible, because I didn't know of any others that did it. I appreciate your enthusiasm, but most of these are more effort than I want to put in (I'm very not good at coming up with jokes for the upgrades and achievements, and the art is an unpleasant chore to me). I can slow down the rockets though.
